# https://docs.ros.org/en/iron/How-To-Guides/Setup-ROS-2-with-VSCode-and-Docker-Container.html
x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - UID=${UID}
      - GID=${GID}
      - USERNAME=${USERNAME}
      - GROUPNAME=${GROUPNAME}
      - PASSWORD=${PASSWORD}
  ipc: host
  tty: true
  network_mode: host
  privileged: true
  environment:
    - DISPLAY=${DISPLAY}
  volumes:
    - ./src:/home/${USERNAME}/dev_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
services:
  dev:
    <<: *base
    container_name: ros2_develop_container
    init: true
  pub:
    <<: *base
    container_name: sample_publisher
    entrypoint:
      - /bin/bash # エントリーポイントを /bin/bash に設定
      - -c
      - |
        cd ~/dev_ws  # ワークスペースに移動
        colcon build  --packages-select sample_publisher  # パッケージをビルド
        ros2 run sample_publisher talker

  # シリアルポートを指定してエージェントを起動
  sub:
    <<: *base
    container_name: sample_subscriber
    init: true
    entrypoint:
      - /bin/bash
      - -c
      - |
        cd ~/dev_ws  # ワークスペースに移動
        colcon build  --packages-select sample_subscriber  # パッケージをビルド
        ros2 run sample_subscriber listener
  serial:
    container_name: micro-ros-agent-serial
    image: microros/micro-ros-agent:humble
    privileged: true
    network_mode: host
    init: true
    volumes:
      - /dev:/dev
    stdin_open: true
    tty: true
    command: serial --dev /dev/ttyACM0 -b 115200
  udp:
    container_name: micro-ros-agent-udp
    image: microros/micro-ros-agent:humble
    command: udp4 -p 8888
    init: true
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
