# https://docs.ros.org/en/iron/How-To-Guides/Setup-ROS-2-with-VSCode-and-Docker-Container.html
x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - UID=${UID}
      - GID=${GID}
      - USERNAME=${USERNAME}
      - GROUPNAME=${GROUPNAME}
      - PASSWORD=${PASSWORD}
  ipc: host
  network_mode: host
  tty: true
  privileged: true
  init: true
  user: "${UID}:${GID}"
  environment:
    - DISPLAY=${DISPLAY}
  volumes:
    - ./src:/home/${USERNAME}/dev_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
services:
  dev:
    <<: *base
    container_name: ros2_develop_container
  pub:
    <<: *base
    container_name: sample_publisher
    working_dir: /home/${USERNAME}/dev_ws
    entrypoint:
      - /bin/bash
      - -c
      - |
        source /opt/ros/humble/setup.bash
        colcon build  --packages-select sample_publisher  
        source ~/dev_ws/install/setup.bash  
        ros2 run sample_publisher talker

  sub:
    <<: *base
    container_name: sample_subscriber
    working_dir: /home/${USERNAME}/dev_ws
    entrypoint:
      - /bin/bash
      - -c
      - |
        source /opt/ros/humble/setup.bash  
        colcon build  --packages-select sample_subscriber  
        source ~/dev_ws/install/setup.bash  
        ros2 run sample_subscriber listener
  serial:
    container_name: micro-ros-agent-serial
    image: microros/micro-ros-agent:humble
    privileged: true
    network_mode: host
    ipc: host
    volumes:
      - /dev:/dev
    profiles: [ "serial" ]
    stdin_open: true
    tty: true
    init: true
    command: serial --dev /dev/ttyACM0 -b 115200
  udp:
    container_name: micro-ros-agent-udp
    image: microros/micro-ros-agent:humble
    privileged: true
    network_mode: host
    ipc: host
    profiles: [ "udp" ]
    stdin_open: true
    tty: true
    init: true
    command: udp4 -p 8888
