version: '3'
services:
  ros:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - PASSWORD=${PASSWORD}
    network_mode: "host"
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./src:/home/${USERNAME}/dev_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
