# https://docs.ros.org/en/iron/How-To-Guides/Setup-ROS-2-with-VSCode-and-Docker-Container.html
x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - UID=${UID}
      - GID=${GID}
      - USERNAME=${USERNAME}
      - GROUPNAME=${GROUPNAME}
      - PASSWORD=${PASSWORD}
  ipc: host
  tty: true
  network_mode: host
  privileged: true
  environment:
    - DISPLAY=${DISPLAY}
  volumes:
    - ./src:/home/${USERNAME}/dev_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
services:
  dev:
    <<: *base
    container_name: ros2_dev
  sample_pub:
    <<: *base
    container_name: ros2_pub
    entrypoint:
      - /bin/bash # エントリーポイントを /bin/bash に設定
      - -c
      - |
        source /opt/ros/humble/setup.bash  # ROS環境をソース
        cd ~/dev_ws  # ワークスペースに移動
        colcon build  --packages-select sample_publisher  # パッケージをビルド
        source ~/dev_ws/install/setup.bash  # インストールされた環境をソース
        ros2 run sample_publisher talker
  micro-ros-agent-serial:
    container_name: micro-ros-agent-serial
    image: microros/micro-ros-agent:humble
    privileged: true
    network_mode: host
    init: true
    volumes:
      - /dev:/dev
    stdin_open: true
    tty: true
    command: serial --dev /dev/ttyACM0 -b 115200
  micro-ros-agent-udp:
    container_name: micro-ros-agent-udp
    image: microros/micro-ros-agent:humble
    command: udp4 -p 8888
    init: true
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true

  # シリアルポートを指定してエージェントを起動
  sample_sub:
    <<: *base
    container_name: ros2_sub
    entrypoint:
      - /bin/bash
      - -c
      - |
        source /opt/ros/humble/setup.bash  # ROS環境をソース
        cd ~/dev_ws  # ワークスペースに移動
        colcon build  --packages-select sample_subscriber  # パッケージをビルド
        source ~/dev_ws/install/setup.bash  # インストールされた環境をソース
        ros2 run sample_subscriber listener
