# https://docs.ros.org/en/iron/How-To-Guides/Setup-ROS-2-with-VSCode-and-Docker-Container.html

version: "3"
x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - UID=${UID}
      - GID=${GID}
      - USERNAME=${USERNAME}
      - GROUPNAME=${GROUPNAME}
      - PASSWORD=${PASSWORD}
  ipc: host
  tty: true
  network_mode: host
  privileged: true
  environment:
    - DISPLAY=${DISPLAY}
  volumes:
    - ./src:/home/${USERNAME}/dev_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
services:
  dev:
    <<: *base
    container_name: ros2_dev
  ros2_publisher:
    <<: *base
    container_name: ros2_publisher
    entrypoint:
      - /bin/bash # エントリーポイントを /bin/bash に設定
      - -c
      - |
        source /opt/ros/humble/setup.bash  # ROS環境をソース
        cd ~/dev_ws  # ワークスペースに移動
        colcon build  --packages-select sample_publisher  # パッケージをビルド
        source ~/dev_ws/install/setup.bash  # インストールされた環境をソース
        ros2 run sample_publisher talker
  micro-ROS-Agent:
    container_name: micro-ros-agent
    image: microros/micro-ros-agent:humble
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
    stdin_open: true
    tty: true
    command: serial --dev /dev/ttyACM0 -b 115200
  # シリアルポートを指定してエージェントを起動
  ros2_subscriber:
    <<: *base
    container_name: ros2_subscriber
    entrypoint:
      - /bin/bash
      - -c
      - |
        source /opt/ros/humble/setup.bash  # ROS環境をソース
        cd ~/dev_ws  # ワークスペースに移動
        colcon build  --packages-select sample_subscriber  # パッケージをビルド
        source ~/dev_ws/install/setup.bash  # インストールされた環境をソース
        ros2 run sample_subscriber listener
