version: '3'
services:
  ros:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - PASSWORD=${PASSWORD}
    network_mode: "host"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./dev_ws:/home/${USERNAME}/dev_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
