version: '3'
services:
  humble_gpu:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    network_mode: "host"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              #count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./ros2_ws:/home/user/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
