version: '3'
services:
  ros:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    network_mode: "host"
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./pkg:/home/user/ros2_ws/src/camera
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
