version: '3'
services:
  ros:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    network_mode: "host"
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./dev_ws:/home/user/dev_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
